# Generated by Django 4.0 on 2022-07-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=5000)),
                ('number', models.CharField(max_length=5)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('artist_link', models.URLField(blank=True, max_length=150, null=True)),
                ('soundcloud_link', models.URLField(blank=True, max_length=150, null=True)),
                ('beatport_link', models.URLField(blank=True, max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
