# Generated by Django 4.0 on 2022-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelrelease',
            name='number',
            field=models.IntegerField(max_length=5),
        ),
    ]
