# Generated by Django 4.0.6 on 2022-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_releases', '0002_alter_labelrelease_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelrelease',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
