# Generated by Django 4.0.6 on 2022-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('artist_name', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=2000)),
                ('soundcloud_link', models.URLField(blank=True, max_length=150, null=True)),
                ('beatport_link', models.URLField(blank=True, max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['artist_name'],
            },
        ),
    ]
