# Generated by Django 4.0 on 2022-07-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle_one', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle_two', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle_three', models.CharField(blank=True, max_length=300, null=True)),
                ('body_one', models.TextField(max_length=5000)),
                ('body_two', models.TextField(blank=True, max_length=5000, null=True)),
                ('body_three', models.TextField(blank=True, max_length=5000, null=True)),
                ('body_four', models.TextField(blank=True, max_length=5000, null=True)),
                ('main_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_two_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_three_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_four_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
