# Generated by Django 4.0 on 2022-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_mixes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmix',
            name='number',
            field=models.IntegerField(max_length=4),
        ),
    ]
