# Generated by Django 4.0.6 on 2022-07-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_mixes', '0002_alter_guestmix_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestmix',
            options={'ordering': ['number']},
        ),
    ]
