# Generated by Django 4.0.6 on 2022-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_mixes', '0004_alter_guestmix_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestmix',
            options={'ordering': ['number'], 'verbose_name_plural': 'Guest Mixes'},
        ),
        migrations.AddField(
            model_name='guestmix',
            name='soundcloud_iframe_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
